import type { Theme } from '@mui/material/styles';

export const homeStyles = (theme: Theme, scrolled: boolean = false) => ({
	landingCard: {
		backgroundColor: theme.palette.secondary.light,
		display: 'flex',
		justifyContent: 'center',
		alignItems: 'center',
		gap: 6,
		borderRadius: 3,
		mb: 4,
		boxShadow: 'none',
		flexWrap: 'wrap',
		typography: {
			color: theme.palette.primary.dark,
			fontSize: '1.5rem',
			[theme.breakpoints.down('sm')]: {
				fontSize: '1rem',
			},
		},
		cardMedia: {
			width: '40%',
			maxWidth: 500,
			minWidth: 220,
			height: 'auto',
			borderRadius: 8,
			maskImage: 'radial-gradient(circle, black 50%, transparent 100%)',
			webkitMaskImage: 'radial-gradient(circle, black 50%, transparent 100%)',
		},
	},
	mainTypo: {
		variant: 'h1',
		fontWeight: 'bolder',
		fontSize: { md: '20vw', xs: '22vw' },
		fontFamily: 'Alegreya',
		textShadow: '5px 8px 12px rgba(0, 0, 0, 0.66)',
		zIndex: 100,
		color: scrolled ? theme.palette.primary.dark : theme.palette.primary.main,
		borderRadius: 2,
		width: '100%',
		textAlign: 'center',
		border: 4,
		borderColor: theme.palette.primary.light,
	},
	landingBtn: {
		backgroundColor: 'inherit',
		background: 'inherit',
		color: theme.palette.primary.dark,
		border: 'none',
		fontWeight: 'bold',
		fontSize: '1rem',
		borderRadius: 0,
		borderBottom: 1,
		transition: 'all 0.3s',
		'&:hover': {
			borderColor: theme.palette.background.default,
			color: theme.palette.background.default,
			fontWeight: 'bolder',
		},
		mt: 4,
	},
	privateMediaCard: {
		width: { xs: '100%', md: '350px' },
		maxWidth: '500px',
		borderRadius: 8,
		maskImage: 'radial-gradient(circle, black 70%, transparent 100%)',
		webkitMaskImage: 'radial-gradient(circle, black 70%, transparent 100%)',
	},
	privateStack: {
		gap: 3,
		display: 'flex',
		alignItems: 'center',
		justifyContent: 'center',
	},
	firstPrivPaper: {
		p: 4,
		borderRadius: 8,
		background: theme.palette.boxColors.tertiary,
		position: 'relative',
		height: '100%',
	},
	firstprivBox: {
		display: 'flex',
		alignItems: 'center',
		justifyContent: 'center',
		gap: 3,
		mb: 2,
		flexWrap: { xs: 'wrap', sm: 'nowrap' },
	},
	secondPrivPaper: {
		display: 'flex',
		gap: 2,
		mt: 3,
		flexDirection: { xs: 'column', md: 'row' },
		background: 'transparent',
		boxShadow: 'none',
	},
});
