import type { Theme } from '@mui/material/styles';

export const recipeStyles = (theme: Theme) => ({
	recipeAside: {
		display: 'flex',
		width: 'fit-content',
		justifyContent: 'center',
		alignItems: 'flex-start',
		minHeight: '100vh',
		paddingTop: 5,
		backgroundColor: '#291e04ff',
		backgroundImage: 'url("/wood-pattern.png")',
		backgroundRepeat: 'repeat',
		backgroundPosition: 'center',
		backgroundSize: 'auto',
		listItemBtn: {
			borderRadius: 2,
			display: 'flex',
			alignItems: 'center',
			justifyContent: 'justify-between',
			gap: 2,
			width: '100%',
			transition: 'background 0.15s, transform 0.15s',
			'&:hover': {
				transform: 'translateY(-2px)',
				backgroundColor: 'rgba(255, 255, 255, 0.17)',
				'& .MuiListItemText-root': {
					color: theme.palette.primary.light,
					filter: 'brightness(1.5)',
				},
			},
		},
		listItemTxt: {
			color: theme.palette.background.paper,
			borderRadius: 2,
			p: 0.5,
			transition: 'background 0.2s',
			fontFamily: 'Alegreya',
		},
		primaryTypoProps: {
			color: theme.palette.primary.main,
			fontWeight: 'bolder',
			transition: 'transform 0.2s',
			'&:hover': {
				transform: 'scale(1.05)',
			},
			fontFamily: 'Alegreya',
		},
		drawerProps: {
			backgroundColor: theme.palette.secondary.light,
			width: 250,
			paddingTop: 5,
			minHeight: '100vh',
		},
	},
	boxContent: {
		width: 200,
		p: 2,
	},
	title: {
		fontSize: '1.5rem',
		mb: 2,
		fontWeight: 'bolder',
		color: theme.palette.primary.main,
		display: 'flex',
		alignItems: 'center',
		gap: 1,
		fontFamily: 'Alegreya',
	},
	recipeDetail: {
		Card: {
			display: 'flex',
			flexDirection: 'column',
			p: 3,
			boxShadow: 6,
			borderRadius: 4,
			gap: 2,
			height: '100%',
			width: '100%',
			maxWidth: '900px',
		},
		mainBox: {
			display: 'flex',
			justifyContent: 'space-around',
			gap: 2,
			flexWrap: { xs: 'wrap', sm: 'nowrap' },
		},
		rightBox: {
			display: 'flex',
			flexDirection: 'column',
			width: '100%',
			border: 2,
			py: 2,
			px: 5,
			borderRadius: 4,
			borderColor: theme.palette.divider,
		},
		leftBox: {
			py: 2,
			px: 5,
			width: '100%',
			borderRadius: 4,
			display: 'flex',
			flexDirection: 'column',
			gap: 2,
			justifyContent: 'space-around',
			border: 2,
			borderColor: theme.palette.divider,
			minHeight: '100%',
			alignItems: 'center',
			flexWrap: 'wrap',
		},
		title: {
			container: {
				display: 'flex',
				justifyContent: 'space-between',
				alignItems: 'center',
				gap: 2,
				border: 2,
				borderColor: theme.palette.divider,
				borderRadius: 3,
				p: 1,
				px: 4,
				flexWrap: { xs: 'wrap', md: 'nowrap' },
			},
		},
	},
});
