import type { Theme } from '@mui/material/styles';

export const recipeStyles = (theme: Theme) => ({
	recipeAside: {
		display: 'flex',
		width: 'fit-content',
		justifyContent: 'center',
		alignItems: 'flex-start',
		minHeight: '100vh',
		backgroundColor: theme.palette.secondary.light,
		paddingTop: 5,
		boxShadow: 'inset 0 20px 40px rgba(0, 0, 0, 0.51)',
	},
	boxContent: {
		width: 200,
		p: 2,
	},
	title: {
		fontSize: '1.5rem',
		mb: 2,
		fontWeight: 'bolder',
		color: theme.palette.background.paper,
		display: 'flex',
		alignItems: 'center',
		gap: 1,
		fontFamily: 'Alegreya',
	},
	recipeDetail: {
		Card: {
			display: 'flex',
			flexDirection: 'column',
			p: 3,
			boxShadow: 6,
			borderRadius: 4,
			gap: 2,
			height: '100%',
			width: '100%',
		},
		mainBox: {
			display: 'flex',
			justifyContent: 'space-around',
			gap: 2,
			flexWrap: { xs: 'wrap', sm: 'nowrap' },
		},
		rightBox: {
			display: 'flex',
			flexDirection: 'column',
			width: '100%',
			border: 2,
			py: 2,
			px: 5,
			borderRadius: 4,
			borderColor: theme.palette.divider,
		},
		leftBox: {
			py: 2,
			px: 5,
			width: '100%',
			borderRadius: 4,
			display: 'flex',
			flexDirection: 'column',
			gap: 2,
			justifyContent: 'space-around',
			border: 2,
			borderColor: theme.palette.divider,
			minHeight: '100%',
			alignItems: 'center',
			flexWrap: 'wrap',
		},
		title: {
			container: {
				display: 'flex',
				justifyContent: 'space-between',
				alignItems: 'center',
				gap: 2,
				border: 2,
				borderColor: theme.palette.divider,
				borderRadius: 3,
				p: 1,
				px: 4,
				flexWrap: { xs: 'wrap', md: 'nowrap' },
			},
		},
	},
});
